// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: msg.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Messaging {

  /// <summary>Holder for reflection information generated from msg.proto</summary>
  public static partial class MsgReflection {

    #region Descriptor
    /// <summary>File descriptor for msg.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static MsgReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cgltc2cucHJvdG8SCW1lc3NhZ2luZyJtCgNNc2cSHwoFdWlNc2cYASABKA4y",
            "EC5tZXNzYWdpbmcuVWlNc2cSIQoGZGxsTXNnGAIgASgOMhEubWVzc2FnaW5n",
            "LkRsbE1zZxIRCglkb3VibGVWYWwYAyABKAESDwoHYm9vbFZhbBgEIAEoCCom",
            "CgVVaU1zZxIMCghTRVRTUEVFRBAAEg8KC1NFVEJQTVNDQUxFEAEqJQoGRGxs",
            "TXNnEg0KCUNPTk5FQ1RFRBAAEgwKCFJFU1BPTlNFEAFiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Messaging.UiMsg), typeof(global::Messaging.DllMsg), }, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Messaging.Msg), global::Messaging.Msg.Parser, new[]{ "UiMsg", "DllMsg", "DoubleVal", "BoolVal" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Enums
  public enum UiMsg {
    [pbr::OriginalName("SETSPEED")] Setspeed = 0,
    [pbr::OriginalName("SETBPMSCALE")] Setbpmscale = 1,
  }

  public enum DllMsg {
    [pbr::OriginalName("CONNECTED")] Connected = 0,
    [pbr::OriginalName("RESPONSE")] Response = 1,
  }

  #endregion

  #region Messages
  public sealed partial class Msg : pb::IMessage<Msg>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Msg> _parser = new pb::MessageParser<Msg>(() => new Msg());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Msg> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Messaging.MsgReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Msg() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Msg(Msg other) : this() {
      uiMsg_ = other.uiMsg_;
      dllMsg_ = other.dllMsg_;
      doubleVal_ = other.doubleVal_;
      boolVal_ = other.boolVal_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Msg Clone() {
      return new Msg(this);
    }

    /// <summary>Field number for the "uiMsg" field.</summary>
    public const int UiMsgFieldNumber = 1;
    private global::Messaging.UiMsg uiMsg_ = global::Messaging.UiMsg.Setspeed;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Messaging.UiMsg UiMsg {
      get { return uiMsg_; }
      set {
        uiMsg_ = value;
      }
    }

    /// <summary>Field number for the "dllMsg" field.</summary>
    public const int DllMsgFieldNumber = 2;
    private global::Messaging.DllMsg dllMsg_ = global::Messaging.DllMsg.Connected;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Messaging.DllMsg DllMsg {
      get { return dllMsg_; }
      set {
        dllMsg_ = value;
      }
    }

    /// <summary>Field number for the "doubleVal" field.</summary>
    public const int DoubleValFieldNumber = 3;
    private double doubleVal_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public double DoubleVal {
      get { return doubleVal_; }
      set {
        doubleVal_ = value;
      }
    }

    /// <summary>Field number for the "boolVal" field.</summary>
    public const int BoolValFieldNumber = 4;
    private bool boolVal_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool BoolVal {
      get { return boolVal_; }
      set {
        boolVal_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Msg);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Msg other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (UiMsg != other.UiMsg) return false;
      if (DllMsg != other.DllMsg) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(DoubleVal, other.DoubleVal)) return false;
      if (BoolVal != other.BoolVal) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (UiMsg != global::Messaging.UiMsg.Setspeed) hash ^= UiMsg.GetHashCode();
      if (DllMsg != global::Messaging.DllMsg.Connected) hash ^= DllMsg.GetHashCode();
      if (DoubleVal != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(DoubleVal);
      if (BoolVal != false) hash ^= BoolVal.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (UiMsg != global::Messaging.UiMsg.Setspeed) {
        output.WriteRawTag(8);
        output.WriteEnum((int) UiMsg);
      }
      if (DllMsg != global::Messaging.DllMsg.Connected) {
        output.WriteRawTag(16);
        output.WriteEnum((int) DllMsg);
      }
      if (DoubleVal != 0D) {
        output.WriteRawTag(25);
        output.WriteDouble(DoubleVal);
      }
      if (BoolVal != false) {
        output.WriteRawTag(32);
        output.WriteBool(BoolVal);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (UiMsg != global::Messaging.UiMsg.Setspeed) {
        output.WriteRawTag(8);
        output.WriteEnum((int) UiMsg);
      }
      if (DllMsg != global::Messaging.DllMsg.Connected) {
        output.WriteRawTag(16);
        output.WriteEnum((int) DllMsg);
      }
      if (DoubleVal != 0D) {
        output.WriteRawTag(25);
        output.WriteDouble(DoubleVal);
      }
      if (BoolVal != false) {
        output.WriteRawTag(32);
        output.WriteBool(BoolVal);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (UiMsg != global::Messaging.UiMsg.Setspeed) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) UiMsg);
      }
      if (DllMsg != global::Messaging.DllMsg.Connected) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) DllMsg);
      }
      if (DoubleVal != 0D) {
        size += 1 + 8;
      }
      if (BoolVal != false) {
        size += 1 + 1;
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Msg other) {
      if (other == null) {
        return;
      }
      if (other.UiMsg != global::Messaging.UiMsg.Setspeed) {
        UiMsg = other.UiMsg;
      }
      if (other.DllMsg != global::Messaging.DllMsg.Connected) {
        DllMsg = other.DllMsg;
      }
      if (other.DoubleVal != 0D) {
        DoubleVal = other.DoubleVal;
      }
      if (other.BoolVal != false) {
        BoolVal = other.BoolVal;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            UiMsg = (global::Messaging.UiMsg) input.ReadEnum();
            break;
          }
          case 16: {
            DllMsg = (global::Messaging.DllMsg) input.ReadEnum();
            break;
          }
          case 25: {
            DoubleVal = input.ReadDouble();
            break;
          }
          case 32: {
            BoolVal = input.ReadBool();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            UiMsg = (global::Messaging.UiMsg) input.ReadEnum();
            break;
          }
          case 16: {
            DllMsg = (global::Messaging.DllMsg) input.ReadEnum();
            break;
          }
          case 25: {
            DoubleVal = input.ReadDouble();
            break;
          }
          case 32: {
            BoolVal = input.ReadBool();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
